#!/usr/bin/env bash
# Idempotent repository bootstrap for the Cloud Agent environment.
# Runs after the repo is checked out. Installs system + node dependencies and
# generates a local .env for development. Must terminate and be safe to re-run.
set -euo pipefail

cd "$(dirname "$0")/.."

echo "==> Ensuring PostgreSQL is installed"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

echo "==> Installing node dependencies (pnpm, frozen lockfile)"
# postinstall runs `prisma generate`.
pnpm install --frozen-lockfile

echo "==> Ensuring local development .env exists"
if [ ! -f .env ]; then
  cat > .env <<'ENV'
# Local Cloud Agent development configuration (auto-generated by .cursor/install.sh).
# Not committed (.env* is gitignored). Replace placeholders with real values via
# Cursor Secrets to exercise external integrations (FAL, Neynar, CDP, Zora).

# Database (local PostgreSQL managed by .cursor/start.sh)
DATABASE_URL=postgresql://appuser:apppass@127.0.0.1:5432/x402miniapp?schema=public

# MiniKit / app metadata
NEXT_PUBLIC_ONCHAINKIT_API_KEY=dev_placeholder_onchainkit_key
NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME=AI Video Generator Mini App
NEXT_PUBLIC_URL=http://localhost:3000
NEXT_PUBLIC_APP_SUBTITLE=Create and share AI-generated videos
NEXT_PUBLIC_APP_DESCRIPTION=Generate and share unique AI videos directly on Farcaster
NEXT_PUBLIC_APP_ICON=/icon.png
NEXT_PUBLIC_APP_SPLASH_IMAGE=/splash.png
NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR=#000000
NEXT_PUBLIC_APP_PRIMARY_CATEGORY=Entertainment
NEXT_PUBLIC_APP_HERO_IMAGE=/hero.png
NEXT_PUBLIC_APP_TAGLINE=AI Video Generation Made Social
NEXT_PUBLIC_APP_OG_TITLE=AI Video Generator Mini App
NEXT_PUBLIC_APP_OG_DESCRIPTION=Create, share, and remix AI-generated videos on Farcaster
NEXT_PUBLIC_APP_OG_IMAGE=/og-image.png

# Farcaster Account Association (placeholders)
FARCASTER_HEADER=dev_placeholder_header
FARCASTER_PAYLOAD=dev_placeholder_payload
FARCASTER_SIGNATURE=dev_placeholder_signature

# Payment Configuration
NEXT_PUBLIC_RESOURCE_WALLET_ADDRESS=0x000000000000000000000000000000000000dEaD
NEXT_PUBLIC_NETWORK=base-sepolia

# x402 facilitator signer (well-known throwaway test key, NEVER use with real funds)
FACILITATOR_PRIVATE_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d

# CDP Wallet Configuration (placeholders)
CDP_API_KEY_ID=dev_placeholder_cdp_key_id
CDP_API_KEY_SECRET=dev_placeholder_cdp_key_secret
CDP_WALLET_SECRET=dev_placeholder_cdp_wallet_secret

# Farcaster API Configuration (placeholders)
NEXT_PUBLIC_NEYNAR_API_KEY=dev_placeholder_neynar_key
NEYNAR_API_KEY=dev_placeholder_neynar_key

# AI Model Configuration (placeholder)
FAL_KEY=dev_placeholder_fal_key

# Redis Configuration (optional; unset -> notifications/webhooks disabled)
# REDIS_URL=
# REDIS_TOKEN=
ENV
  echo "    Created .env with local development defaults."
else
  echo "    .env already present; leaving it unchanged."
fi

echo "==> install.sh complete"
